-- CreateTable
CREATE TABLE "Scan" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "scannedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "linkId" TEXT NOT NULL,
    CONSTRAINT "Scan_linkId_fkey" FOREIGN KEY ("linkId") REFERENCES "Links" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
